{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "coraza-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coraza-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.prometheusRule.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: coraza.operator.engines
      rules:
        - alert: CorazaEngineNotReady
          expr: count(coraza_engine_condition{condition="Ready"} == 0) > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Coraza Engine(s) not ready"
            description: "{{ "{{" }} $value {{ "}}" }} Coraza Engine(s) are not in the Ready state for more than 5 minutes."
        - record: coraza:engines_not_ready:count
          expr: count(coraza_engine_condition{condition="Ready"} == 0) or vector(0)
    - name: coraza.operator.recording
      rules:
        - record: coraza:engines_ready:count
          expr: sum(coraza_engine_condition{condition="Ready"} == 1) or vector(0)
        - record: coraza:rulesets_ready:count
          expr: sum(coraza_ruleset_condition{condition="Ready"} == 1) or vector(0)
{{- end }}
