name: Issue Management

permissions:
  contents: read

on:
  issues:
    types:
      [opened, reopened, edited, labeled, unlabeled, milestoned, demilestoned]

jobs:
  manage:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request }}
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          sparse-checkout: tools/github_project_manager
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: tools/github_project_manager/go.mod

      - name: Verify go module integrity
        working-directory: tools/github_project_manager
        run: go mod verify

      - name: Build project manager
        working-directory: tools/github_project_manager
        run: go build -o "${{ github.workspace }}/github_project_manager" .

      - name: Close declined issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
          GITHUB_EVENT_REPOSITORY_NAME: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          ./github_project_manager -v \
            --owner "${GITHUB_REPO_OWNER}" \
            --repo "${GITHUB_EVENT_REPOSITORY_NAME}" \
            --issue "${ISSUE_NUMBER}" \
            close-declined

      - name: Update labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
          GITHUB_EVENT_REPOSITORY_NAME: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          ./github_project_manager -v \
            --owner "${GITHUB_REPO_OWNER}" \
            --repo "${GITHUB_EVENT_REPOSITORY_NAME}" \
            --issue "${ISSUE_NUMBER}" \
            update-labels
