name: pr management

permissions: read-all

on:
    pull_request_target:
        types: [opened, synchronize, reopened]

jobs:
    triage:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
            issues: write
            projects: write
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  ref: ${{ github.event.pull_request.base.sha }}
                  sparse-checkout: tools/cmd/github_project_manager
                  persist-credentials: false

            - name: Setup Go
              uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
              with:
                  go-version-file: tools/cmd/github_project_manager/go.mod

            - name: Build project manager
              working-directory: tools/cmd/github_project_manager
              run: go build -o "${{ github.workspace }}/github_project_manager" .

            - name: Triage PR
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_EVENT_REPOSITORY_NAME: ${{ github.event.repository.name }}
              run: |
                  ./github_project_manager -v \
                    --owner "${{ github.repository_owner }}" \
                    --repo "${GITHUB_EVENT_REPOSITORY_NAME}" \
                    --issue "${{ github.event.pull_request.number }}" \
                    triage-pr
